version: '3'

includes:
  db:
    taskfile: ./Taskfile_db.yml
    dir: .

tasks:
  setup:
    desc: 
  build:
    desc: Rebuild app (if changed) from docker compose
    cmds:
      - docker-compose build app

  start:
    desc: Restart app (and rebuild if changed) from docker compose
    cmds:
      - docker-compose up -d app
    deps:
      - build

  logs:
    desc: Attach to docker compose logs for app
    cmds:
      - docker-compose logs -f app

  start+logs:
    desc: Alias for 'start' followed by 'logs'
    cmds:
      - task: start
      - task: logs

  stop:
    desc: Stop all containers
    cmds:
      - docker-compose down

  destroy:
    desc: Destroy all images (one level)
    cmds:
      - docker-compose down --rmi local --remove-orphans

  destroy:more:
    desc: Destroy all images (one level) and volumes
    cmds:
      - docker-compose down --rmi local -v --remove-orphans

  lint:
    desc: Run app linting
    cmds:
      - task: exec:docker
        vars: {CLI_ARGS: pylint --jobs=0 src test}

  test:
    desc: Run app tests
    cmds:
      - task: exec:docker
        vars: {CLI_ARGS: python -m unittest discover -s test -p '*_test.py'}

  exec:docker:
    desc: Execute a command inside an new Docker container instance
    cmds:
      - docker-compose run --rm -T app bash -c "{{.CLI_ARGS}}"
    deps:
      - build
