version: '3'

includes:
  app:
    taskfile: ./app
    dir: ./app

  ui:
    taskfile: ./ui
    dir: ./ui

  db:
    taskfile: ./db
    dir: ./db

tasks:
  destroy:
    cmds:
      - docker compose down

  start:
    cmds:
      - docker compose up
    deps:
      - down

  logs:
    cmds:
      - docker compose logs -f
    deps:
      - start
