version: '3'

includes:
  app:
    taskfile: ./app/tasks/Taskfile_{{OS}}.yml
    dir: ./app

  ui:
    taskfile: ./ui
    dir: ./ui

  db:
    taskfile: ./Taskfile_db.yml
    dir: .

tasks:
  default: source ./art.sh

  destroy:
    desc: Delete images, volumes and containers from docker compose
    cmds:
      - docker-compose down

  start:
    desc: Start all containers from docker compose
    cmds:
      - docker-compose up -d db
    deps:
      - task: app:start
      - task: ui:start

  logs:
    desc: Attach to docker compose logs
    cmds:
      - docker-compose logs -f

  start+logs:
    desc: Alias for 'start' followed by 'logs'
    cmds:
      - task: start
      - task: logs
