version: '3'

tasks:
  build:
    deps:
      - build/app
      - build/ui
      - build/db

  build/app:
    cmds:
      - docker compose build app
    sources:
      - 'app/**/*.*'

  build/ui:
    cmds:
      - docker compose build ui
    sources:
      - 'ui/**/*.*'

  build/db:
    cmds:
      - docker compose build db
    sources:
      - 'bd_init/**/*.*'

  up:
    cmds:
      - docker compose up --remove-orphans
    deps:
      - down
      - build

  down:
    cmds:
      - docker compose down
