version: '3'

includes:
  app:
    taskfile: ./app
    dir: ./app

  ui:
    taskfile: ./ui
    dir: ./ui

  db:
    taskfile: ./db
    dir: ./db

tasks:
  default: source ./art.sh

  destroy:
    desc: Delete images, volumes and containers from docker compose
    cmds:
      - docker compose down

  start:
    desc: Force-rebuild and restart all containers from docker compose
    cmds:
      - task: db:build
      - task: app:build
      - task: ui:build
      - docker compose up -d

  logs:
    desc: Attach to docker compose logs
    cmds:
      - docker compose logs -f

  start+logs:
    desc: Alias for 'start' followed by 'logs'
    cmds:
      - task: start
      - task: logs
