version: '3'

tasks:
  build:
    deps:
      - build:app
      - build:ui
      - build:db

  build:app:
    cmds:
      - docker compose build app
    sources:
      - 'app/**/*.*'

  build:ui:
    cmds:
      - docker compose build ui
    sources:
      - 'ui/**/*.*'

  build:db:
    cmds:
      - docker compose rm -s -v -f db
      - docker compose build db
    sources:
      - 'db/**/*.*'

  start:ui:
    cmds:
      - docker compose up -d ui
    deps:
      - build:ui

  start:app:
    cmds:
      - docker compose up -d app
    deps:
      - build:app

  start:db:
    cmds:
      - docker compose up -d db
    deps:
      - build:db

  logs:app:
    cmds:
      - docker compose logs -f app
    deps:
      - start:app

  logs:ui:
    cmds:
      - docker compose logs -f ui
    deps:
      - start:ui

  logs:db:
    cmds:
      - docker compose logs -f db
    deps:
      - start:db
