version: '3'

includes:
  app:
    taskfile: ./app
    dir: ./app

  ui:
    taskfile: ./ui
    dir: ./ui

  db:
    taskfile: ./Taskfile_db.yml
    dir: .

tasks:
  default: source ./art.sh

  stop:
    desc: Stop all containers
    cmds:
      - docker-compose down

  start:
    desc: Start all containers from docker compose
    cmds:
      - task: db:start
      - task: app:start
      - task: ui:start

  destroy:
    desc: Destroy all images (one level)
    cmds:
      - docker-compose down --rmi local --remove-orphans

  destroy:more:
    desc: Destroy all images (one level) and volumes
    cmds:
      - docker-compose down --rmi local -v --remove-orphans

  logs:
    desc: Attach to docker compose logs
    cmds:
      - docker-compose logs -f

  start+logs:
    desc: Alias for 'start' followed by 'logs'
    cmds:
      - task: start
      - task: logs

  setup:local:
    desc: Setup all services to be ready for use
    cmds:
      - task: db:start
      - task: app:migration:apply
      - task: app:populate
