version: '3'

vars:
  VENV_DIR: .venv
  VENV_ACTIVATE: .venv/bin/activate

tasks:
  venv:setup:
    desc: Creates virtual env and installs dependencies
    cmds:
      - python3 -m venv "{{.VENV_DIR}}"
      - source "{{.VENV_ACTIVATE}}" && pip install --upgrade pip && pip install -r requirements.txt
    status:
      - test -d "{{.VENV_DIR}}"

  venv:path:
    desc: Displays the virtual env path activation script
    cmds:
      - echo "$PWD/{{.VENV_ACTIVATE}}"
    silent: true
    deps:
      - venv:setup

  test:
    desc: Run app tests (within virtual env)
    cmds:
      - source "{{.VENV_ACTIVATE}}" && python -m unittest discover -s test -p '*_test.py'
    deps:
      - venv:setup

  lint:
    desc: Run app linting (within virtual env)
    cmds:
      - source "{{.VENV_ACTIVATE}}" && pylint app && pylint test
    deps:
      - venv:setup

  build:
    desc: Rebuild app (if changed) from docker compose
    dir: ..
    cmds:
      - docker-compose build app
    sources:
      - ./app/**/*.*

  start:
    desc: Restart app (and rebuild if changed) from docker compose
    dir: ..
    cmds:
      - task: migration:apply
      - docker-compose up -d app
    deps:
      - build

  logs:
    desc: Attach to docker compose logs for app
    dir: ..
    cmds:
      - docker-compose logs -f app

  start+logs:
    desc: Alias for 'start' followed by 'logs'
    cmds:
      - task: start
      - task: logs

  migration:apply:
    desc: Apply new database changes
    cmds:
      - source "{{.VENV_ACTIVATE}}" && python ./app/scripts/migrate.py
    deps:
      - venv:setup

  migration:rollback:
    desc: Rollback last database change
    cmds:
      - source "{{.VENV_ACTIVATE}}" && python ./app/scripts/rollback.py
    deps:
      - venv:setup

  migration:new:
    desc: Create new database migration
    cmds:
      - source "{{.VENV_ACTIVATE}}" && yoyo new ./migrations -m "{{.DESC}}"
    deps:
      - venv:setup

  populate:
    desc: Fill database with fake data
    cmds:
      - source "{{.VENV_ACTIVATE}}" && python -m app.scripts.fill_db
    deps:
      - venv:setup
