database:
  host: $MYSQL_HOST|localhost
  port: $MYSQL_PORT|8082
  user: api
  password: '1234'
  root-password: '12345'
  database: cooky

flask:
  secret: secret
  jwt:
    expiration-in-minutes: 30
