version: '3'

tasks:
  test:
    cmds:
      - python -m unittest discover -s test -p '*_test.py'

  lint:
    cmds:
      - pylint app && pylint test

  build:
    dir: '..'
    cmds:
      - docker compose build app
    sources:
      - '**/*.*'

  start:
    dir: '..'
    cmds:
      - docker compose up -d app
    deps:
      - build

  logs:
    dir: '..'
    cmds:
      - docker compose logs -f app
    deps:
      - start
