version: '3'

tasks:
  build:
    desc: Rebuild db (if changed) from docker compose
    dir: '..'
    cmds:
      - docker compose rm -s -v -f db
      - docker compose build db
    sources:
      - '**/*.*'

  start:
    desc: Restart db (and rebuild if changed) from docker compose
    dir: '..'
    cmds:
      - docker compose up -d db
    deps:
      - build

  logs:
    desc: Attach to docker compose logs for db
    dir: '..'
    cmds:
      - docker compose logs -f db

  start+logs:
    desc: Alias for 'start' followed by 'logs'
    cmds:
      - task: start
      - task: logs

  exec:
    desc: Execute mysql inside the db container
    dir: '..'
    cmds:
      - docker compose exec db mysql -u root -p
