version: '3'

tasks:
  build:
    dir: '..'
    cmds:
      - docker compose rm -s -v -f db
      - docker compose build db
    sources:
      - '**/*.*'

  start:
    dir: '..'
    cmds:
      - docker compose up -d db
    deps:
      - build

  logs:
    dir: '..'
    cmds:
      - docker compose logs -f db
    deps:
      - start
