version: '3'

tasks:
  build:
    dir: '..'
    cmds:
      - docker compose build ui
    sources:
      - '**/*.*'

  start:
    dir: '..'
    cmds:
      - docker compose up -d ui
    deps:
      - build

  logs:
    dir: '..'
    cmds:
      - docker compose logs -f ui
    deps:
      - start
