version: '3'

tasks:
  build:
    desc: Rebuild ui (if changed) from docker compose
    dir: '..'
    cmds:
      - docker compose build ui
    sources:
      - '**/*.*'

  start:
    desc: Restart ui (and rebuild if changed) from docker compose
    dir: '..'
    cmds:
      - docker compose up -d ui
    deps:
      - build

  logs:
    desc: Attach to docker compose logs for ui
    dir: '..'
    cmds:
      - docker compose logs -f ui

  start+logs:
    desc: Alias for 'start' followed by 'logs'
    cmds:
      - task: start
      - task: logs
