version: '3'

tasks:
  build:docker:
    desc: Rebuild ui (if changed) from docker compose
    dir: ..
    cmds:
      - docker-compose build ui

  build:
    desc: Build node project inside Docker machine
    cmds:
      - task: exec:docker
        vars: {CLI_ARGS: yarn build}

  lint:
    desc: Lint files
    cmds:
      - task: exec:docker
        vars: {CLI_ARGS: yarn lint}

  start:
    desc: Restart ui (and rebuild if changed) from docker compose
    cmds:
      - docker-compose up -d ui
    deps:
      - build:docker

  logs:
    desc: Attach to docker compose logs for ui
    cmds:
      - docker-compose logs -f ui

  start+logs:
    desc: Alias for 'start' followed by 'logs'
    cmds:
      - task: start
      - task: logs

  exec:docker:
    desc: Execute a command inside an new Docker container instance
    cmds:
      - docker-compose run --rm -T ui sh -c "{{.CLI_ARGS}}"
    deps:
      - build:docker
