name: Build

on:
  push:
    branches-ignore:
      - "master"

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v2
      
      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          version: '3.x'

      - name: Building Docker image
        run: task app:build:docker

      - name: Linting
        run: task app:lint

      - name: Testing
        run: task app:test


  build-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          version: '3.x'

      - name: Building Docker image
        run: task ui:build:docker

      - name: Linting
        run: task ui:lint

      - name: Building
        run: task ui:build
